### ISSUE TITLE
Problem of translation on neufing.org

### ISSUE THREAD

**Issue by TylerTemp** [ejjoman/harbour-sailfishreboot#3]
Hi, I'm trying to translate this project into Chinese on [neufing](https://translate.neufing.org/projects/sailfishreboot/). But after translating, all the Chinese characters became "???".

Does this the bug of neufing or of the project settings?(I've already report it to neufing) Can you see the the real Chinese string at your side?

And sorry to bother you here since there is no "issue" page on neufing.org

OS: Ubuntu 14.10
Browser: Firefox Developer Edition 38.0a2 (2015-03-12)

**Comment by ejjoman** [comment]
Hi,
sorry for this error - I set up the database with the wrong character set (latin), so non-latin characters got removed :(
I changed the character set to UTF8 now and it seems to work now.

But you have to re-enter all entries again, unfortunately :(

Sorry for the inconvenience.
